language: perl
perl:
  - "5.18"
sudo: required

services:
  - docker

install:
  - sudo pip install nose2
  - cpanm install Devel::Cover
script:
  - pushd Bio-KBase-Auth
  - perl Build.PL
  - ./Build installdeps --cpan_client 'cpanm'
  - ./Build test

